### ISSUE TITLE
fork from rbenv-default-gems rather than copy?

### ISSUE THREAD

**Issue by jasonkarns** [nicknovitski/nodenv-default-packages#2]
I would have liked to have seen this plugin forked from rbenv-default-gems rather than copied. If they shared a common commit history, it would have made it trivial to merge in any 'upstream' changes.

I wouldn't mind doing the work to graft the history back in, if it would be of interest. Personally, I would feel much more comfortable with the stability of this plugin if I knew that any bugfixes/security fixes/performance improvements that get made to upstream were easily applied here as well. Especially since the rbenv (at least presently) has a much higher user base and active contributors.

Would this be of interest?

**Comment by jasonkarns** [comment]
I've already done similar merges for nodenv (https://github.com/OiNutter/nodenv/pull/14), node-build (https://github.com/OiNutter/node-build/pull/51), nodenv-update (https://github.com/charlesbjohnson/nodenv-update/pull/1), and nodenv-vars (https://github.com/OiNutter/nodenv-vars/pull/2). (I'm the creator of nodenv-each so I ensured its history included rbenv-each from the beginning.)

**Comment by jawshooah** [comment]
@jasonkarns FWIW I independently created my own [nodenv-default-packages](https://github.com/jawshooah/nodenv-default-packages) plugin that's forked from rbenv-default-gems.

**Comment by nicknovitski** [comment]
Hmm, sorry for the late reply.  @jasonkarns you're quite right.  Does jawshooah's fork meet your needs? If so I can just delete this repository in favor of his.

**Comment by jasonkarns** [comment]
@nicknovitski yeah, i've been using @jawshooah's for a bit
